DEF CATEGORY_PROGRAM EQU $01
DEF CATEGORY_APPEND  EQU $04

DEF APPEND_GOROUS_ROPE_PUZZLE EQU 1
DEF APPEND_SLIDING_TILE_PUZZLE EQU 5

DEF GENRE_MISC       EQU $00
DEF GENRE_ACTION     EQU $01
DEF GENRE_PUZZLE     EQU $02
DEF GENRE_PLATFORMER EQU $03
DEF GENRE_RPG        EQU $04
DEF GENRE_SIMULATION EQU $05
DEF GENRE_SHOOTER    EQU $06
DEF GENRE_ADVENTURE  EQU $07
