; joypad buttons
DEF A_BUTTON_F EQU 0
DEF B_BUTTON_F EQU 1
DEF SELECT_F   EQU 2
DEF START_F    EQU 3
DEF D_RIGHT_F  EQU 4
DEF D_LEFT_F   EQU 5
DEF D_UP_F     EQU 6
DEF D_DOWN_F   EQU 7

DEF NO_INPUT   EQU %00000000
DEF A_BUTTON   EQU 1 << A_BUTTON_F
DEF B_BUTTON   EQU 1 << B_BUTTON_F
DEF SELECT     EQU 1 << SELECT_F
DEF START      EQU 1 << START_F
DEF D_RIGHT    EQU 1 << D_RIGHT_F
DEF D_LEFT     EQU 1 << D_LEFT_F
DEF D_UP       EQU 1 << D_UP_F
DEF D_DOWN     EQU 1 << D_DOWN_F

DEF BUTTONS    EQU A_BUTTON | B_BUTTON | SELECT | START
DEF D_PAD      EQU D_RIGHT | D_LEFT | D_UP | D_DOWN

DEF R_DPAD     EQU %00100000
DEF R_BUTTONS  EQU %00010000
